FROM public.ecr.aws/lambda/python:3.11.2024.02.07.18

# Install Python and zip
RUN yum install -y git

# Set up a working directory
WORKDIR /var/task

# Copy the requirements.txt file into the container
COPY package/requirements.txt .
COPY lambda_functions_nlp.py .

COPY nlp ./nlp/
COPY util ./util/
COPY llm ./llm/
COPY package/shared ./shared/

# Install the Python dependencies and package them in a zip file
RUN python3 -m pip install -r requirements.txt

CMD [ "$LAMBDA_FILE.$LAMBDA_HANDLER" ]
