FROM public.ecr.aws/lambda/python:3.12

# Install Python and zip
RUN dnf install -y git

# Set up a working directory
WORKDIR /var/task

# Copy the requirements.txt file into the container
COPY package/requirements.txt .
COPY lambda_function.py .

COPY llm ./llm/
COPY service ./service/
COPY util ./util/

# Install the Python dependencies and package them in a zip file
RUN python3 -m pip install -r requirements.txt

CMD [ "lambda_function.$FUNCTION_handler" ]